# Generated by Django 3.2.7 on 2021-09-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiligarlic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
